language: python
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy3"
# command to install
install: pip install pylint
# command to run tests
script: nosetests
sudo: false
matrix:
  fast_finish: true
after_success:
  - pylint calcul -d line-too-long
